# Generated by Django 4.2.5 on 2023-09-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.IntegerField(),
        ),
    ]
