# Generated by Django 4.2.5 on 2023-09-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0002_alter_doctor_number_alter_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='master',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='ailment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
