# Generated by Django 4.2.5 on 2023-09-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0003_doctor_master_patient_ailment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='feedback',
            field=models.CharField(default='', max_length=250),
        ),
    ]
